server:
  port: 10019

spring:
  main:
    web-application-type: none
  application:
    name: mcp-nacos-client-example
  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC

    alibaba:
      mcp:
        nacos:
          client:
            lazy-init: true
            enabled: true
            sse:
              connections:
                sse-server:
                  service-name: nacos-mcp-server-sse
                  version: 1.0.0
            streamable:
              connections:
                streamable-server:
                  service-name: nacos-mcp-server-streamable
                  version: 1.0.0
            configs:
              sse-server:
                namespace: public
                server-addr: 127.0.0.1:8848
                username: nacos
                password: nacos
              streamable-server:
                namespace: public
                server-addr: 127.0.0.1:8848
                username: nacos
                password: nacos

# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG