server:
  port: 10017

spring:
  application:
    name: nacos-prompt
  profiles:
    active: dev
  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
    nacos:
      prompt:
        template:
          enabled: true
  nacos:
    server-addr: 127.0.0.1:8848
    config:
      username: nacos
      password: nacos
    