server:
  port: 10036
spring:
  application:
    name: a2a-server-example

  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
    alibaba:
      a2a:
        nacos:
          server-addr: localhost:8848
          username: nacos
          password: nacos
          discovery:
            enabled: true
          registry:
            enabled: true
        server:
          type: JSONRPC
          version: 1.0.0
          card:
            name: SaaAgent
            url: http://127.0.0.1:9999/a2a
            skills:
              - id: SAA-answer
                name: SAA Answer
                description: Answer questions about Spring AI Alibaba.
                tags:
                  - SAA
                examples:
                  - What is Spring AI Alibaba?
            icon-url: https://img.alicdn.com/imgextra/i4/O1CN01rW3vAB1FDWKSOiFf0_!!6000000000453-2-tps-204-40.png
            documentation-url: https://www.alibaba.com
            provider:
              organization: Alibaba
              url: https://www.alibaba.com
logging:
  level:
    root: debug