server:
  port: 10031
spring:
  application:
    name: spring-ai-evaluation
  profiles:
    active: dev
  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
      embedding:
        options:
          model: text-embedding-v3

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.example.wx.controller: debug