server:
  port: 10032

spring:
  profiles:
    active: dev
  application:
    name: nacos-mcp-server-streamable
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: nacos-mcp-server-streamable
        version: 1.0.0
        protocol: STREAMABLE
        type: sync
        instructions: "天气查询"
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
    alibaba:
      mcp:
        nacos:
          server-addr: localhost:8848
          namespace: public
          register:
            enabled: true
            service-name: nacos-mcp-server-streamable
            service-group: mcp-server
            service-register: true
            service-ephemeral: true
          username: nacos
          password: nacos


