server:
  port: 10018

spring:
  profiles:
    active: dev
  application:
    name: nacos-mcp-server
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: nacos-mcp-server
        version: 1.0.0
        type: async
        instructions: "This reactive server provides time information tools and resources"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
    alibaba:
      mcp:
        nacos:
          server-addr: localhost:8848
          namespace: public
          register:
            enabled: true
            service-name: webflux-mcp-server
            service-group: mcp-server
            service-register: true
            service-ephemeral: true
          username: nacos
          password: nacos


