server:
  port: 10037

spring:
  application:
    name: a2s-client-example
  ai:
    alibaba:
      a2a:
        nacos:
          discovery:
            enabled: true
          registry:
            enabled: false
          server-addr:  ${NACOS_ADDRESS:localhost:8848}
          username: ${NACOS_USERNAME:nacos}
          password: ${NACOS_PASSWORD}

logging:
  level:
    root: debug